import Head from "next/head";
import { prefix } from "../constants";
import { FC } from "react";

const Header: FC = () => (
  <Head>
    <title>Create Next App</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href={prefix + "/favicon.ico"} />
  </Head>
);

export default Header;
