import Head from 'next/head'
const prefix: string = process.env.NEXT_PUBLIC_BASE_PATH || '';
const Header = () =>
    <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={prefix + "/favicon.ico"} />
    </Head>
export default Header
